"""add activity audit history

Revision ID: 3f6625ce5331
Revises: 6b2fe377e2fe
Create Date: 2026-09-19 22:10:10.582815
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3f6625ce5331'
down_revision: Union[str, Sequence[str], None] = '6b2fe377e2fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_client_id', sa.UUID(), nullable=True),
    sa.Column('actor_name', sa.String(length=120), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=12), nullable=False),
    sa.Column('operation', sa.String(length=512), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('path_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['actor_client_id'], ['api_clients.id'], name=op.f('fk_activity_events_actor_client_id_api_clients'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_events'))
    )
    op.create_index(op.f('ix_activity_events_actor_client_id'), 'activity_events', ['actor_client_id'], unique=False)
    op.create_index(op.f('ix_activity_events_created_at'), 'activity_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_events_domain'), 'activity_events', ['domain'], unique=False)
    op.create_index(op.f('ix_activity_events_entity_id'), 'activity_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_activity_events_method'), 'activity_events', ['method'], unique=False)
    op.create_index(op.f('ix_activity_events_request_id'), 'activity_events', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_events_request_id'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_method'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_entity_id'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_domain'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_created_at'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_actor_client_id'), table_name='activity_events')
    op.drop_table('activity_events')
    # ### end Alembic commands ###
