"""add personal profile

Revision ID: 67193b1daa68
Revises: c1ef83ca66c6
Create Date: 2026-09-19 21:03:32.657359
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '67193b1daa68'
down_revision: Union[str, Sequence[str], None] = 'c1ef83ca66c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_profile',
    sa.Column('singleton_key', sa.SmallInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=32), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint('singleton_key = 1', name=op.f('ck_personal_profile_singleton')),
    sa.PrimaryKeyConstraint('singleton_key', name=op.f('pk_personal_profile'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_profile')
    # ### end Alembic commands ###
