"""add resources

Revision ID: 6b2fe377e2fe
Revises: 43b916c1d71c
Create Date: 2026-09-19 21:45:11.600399
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6b2fe377e2fe'
down_revision: Union[str, Sequence[str], None] = '43b916c1d71c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('resource_type', sa.Enum('book', 'paper', 'course', 'article', 'video', 'documentation', 'repository', 'website', 'file', 'tool', 'other', name='resource_type'), nullable=False),
    sa.Column('status', sa.Enum('saved', 'active', 'completed', 'archived', name='resource_status'), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('local_path', sa.String(length=1024), nullable=True),
    sa.Column('author', sa.String(length=240), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('progress_percent >= 0 AND progress_percent <= 100', name=op.f('ck_resources_progress_percent')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources'))
    )
    op.create_index(op.f('ix_resources_deleted_at'), 'resources', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_resources_resource_type'), 'resources', ['resource_type'], unique=False)
    op.create_index(op.f('ix_resources_status'), 'resources', ['status'], unique=False)
    op.create_table('resource_skills',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_resource_skills_resource_id_resources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_resource_skills_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id', 'skill_id', name=op.f('pk_resource_skills'))
    )
    op.create_index(op.f('ix_resource_skills_skill_id'), 'resource_skills', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_skills_skill_id'), table_name='resource_skills')
    op.drop_table('resource_skills')
    op.drop_index(op.f('ix_resources_status'), table_name='resources')
    op.drop_index(op.f('ix_resources_resource_type'), table_name='resources')
    op.drop_index(op.f('ix_resources_deleted_at'), table_name='resources')
    op.drop_table('resources')
    # ### end Alembic commands ###
