"""add rules engine

Revision ID: 84936d53018a
Revises: 3f6625ce5331
Create Date: 2026-09-20 16:49:09.216564
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '84936d53018a'
down_revision: Union[str, Sequence[str], None] = '3f6625ce5331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain', sa.Enum('task', 'project', 'goal', 'resource', 'skill', name='rule_domain'), nullable=False),
    sa.Column('match_mode', sa.Enum('all', 'any', name='rule_match_mode'), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rules'))
    )
    op.create_index(op.f('ix_rules_deleted_at'), 'rules', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_rules_domain'), 'rules', ['domain'], unique=False)
    op.create_index(op.f('ix_rules_enabled'), 'rules', ['enabled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rules_enabled'), table_name='rules')
    op.drop_index(op.f('ix_rules_domain'), table_name='rules')
    op.drop_index(op.f('ix_rules_deleted_at'), table_name='rules')
    op.drop_table('rules')
    # ### end Alembic commands ###
