"""link goals and projects

Revision ID: 87b99652415d
Revises: cbf4ee7dba43
Create Date: 2026-09-18 23:50:49.754070
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '87b99652415d'
down_revision: Union[str, Sequence[str], None] = 'cbf4ee7dba43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_projects',
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('fk_goal_projects_goal_id_goals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_goal_projects_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('goal_id', 'project_id', name=op.f('pk_goal_projects'))
    )
    op.create_index(op.f('ix_goal_projects_project_id'), 'goal_projects', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goal_projects_project_id'), table_name='goal_projects')
    op.drop_table('goal_projects')
    # ### end Alembic commands ###
