"""create projects

Revision ID: 88d039382c66
Revises: 
Create Date: 2026-09-16 21:54:20.044406
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '88d039382c66'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'PAUSED', 'COMPLETED', 'ABANDONED', name='project_status'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'CRITICAL', name='project_priority'), nullable=False),
    sa.Column('focus_rank', sa.SmallInteger(), nullable=True),
    sa.Column('progress_percent', sa.SmallInteger(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_project_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('focus_rank IS NULL OR focus_rank >= 1', name=op.f('ck_projects_focus_rank_positive')),
    sa.CheckConstraint('parent_project_id IS NULL OR parent_project_id <> id', name=op.f('ck_projects_parent_not_self')),
    sa.CheckConstraint('progress_percent IS NULL OR (progress_percent >= 0 AND progress_percent <= 100)', name=op.f('ck_projects_progress_percent_range')),
    sa.ForeignKeyConstraint(['parent_project_id'], ['projects.id'], name=op.f('fk_projects_parent_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_deleted_at'), 'projects', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_projects_focus_rank'), 'projects', ['focus_rank'], unique=False)
    op.create_index(op.f('ix_projects_parent_project_id'), 'projects', ['parent_project_id'], unique=False)
    op.create_index(op.f('ix_projects_priority'), 'projects', ['priority'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_target_date'), 'projects', ['target_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_target_date'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_priority'), table_name='projects')
    op.drop_index(op.f('ix_projects_parent_project_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_focus_rank'), table_name='projects')
    op.drop_index(op.f('ix_projects_deleted_at'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
