"""add api clients

Revision ID: c1ef83ca66c6
Revises: 87b99652415d
Create Date: 2026-09-19 20:50:30.844692
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c1ef83ca66c6'
down_revision: Union[str, Sequence[str], None] = '87b99652415d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('key_prefix', sa.String(length=24), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_clients'))
    )
    op.create_index(op.f('ix_api_clients_revoked_at'), 'api_clients', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_api_clients_token_hash'), 'api_clients', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_clients_token_hash'), table_name='api_clients')
    op.drop_index(op.f('ix_api_clients_revoked_at'), table_name='api_clients')
    op.drop_table('api_clients')
    # ### end Alembic commands ###
